spring.datasource.url=jdbc:postgresql://database-2.caxwo4geqa52.us-east-1.rds.amazonaws.com:5432/expense_db
spring.datasource.username=postgres
spring.datasource.password=Efb4FoP5ngCobmRme6J3
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080