# ===== PRODUCTION ENVIRONMENT =====
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

server.port=8080